package main

// #include <badge-ir-game-protocol.h>
import "C"
import "fmt"

func showOpcodes() {
	fmt.Println("BADGE_IR_GAME_ADDRESS", C.BADGE_IR_GAME_ADDRESS)
	fmt.Println("OPCODE_SET_GAME_START_TIME", C.OPCODE_SET_GAME_START_TIME)
	fmt.Println("OPCODE_SET_GAME_DURATION", C.OPCODE_SET_GAME_DURATION)
	fmt.Println("OPCODE_HIT", C.OPCODE_HIT)
	fmt.Println("OPCODE_SET_BADGE_TEAM", C.OPCODE_SET_BADGE_TEAM)
	fmt.Println("OPCODE_REQUEST_BADGE_DUMP", C.OPCODE_REQUEST_BADGE_DUMP)
	fmt.Println("OPCODE_SET_GAME_VARIANT", C.OPCODE_SET_GAME_VARIANT)
	fmt.Println("GAME_VARIANT_FREE_FOR_ALL", C.GAME_VARIANT_FREE_FOR_ALL)
	fmt.Println("GAME_VARIANT_TEAM_BATTLE", C.GAME_VARIANT_TEAM_BATTLE)
	fmt.Println("GAME_VARIANT_ZOMBIE", C.GAME_VARIANT_ZOMBIE)
	fmt.Println("GAME_VARIANT_CAPTURE_THE_BADGE", C.GAME_VARIANT_CAPTURE_THE_BADGE)
	fmt.Println("GAME_VARIANT_NONE", C.GAME_VARIANT_NONE)
	fmt.Println("OPCODE_BADGE_RECORD_COUNT", C.OPCODE_BADGE_RECORD_COUNT)
	fmt.Println("OPCODE_BADGE_UPLOAD_HIT_RECORD_BADGE_ID", C.OPCODE_BADGE_UPLOAD_HIT_RECORD_BADGE_ID)
	fmt.Println("OPCODE_GAME_ID", C.OPCODE_GAME_ID)
	fmt.Println("OPCODE_BADGE_UPLOAD_HIT_RECORD_TIMESTAMP", C.OPCODE_BADGE_UPLOAD_HIT_RECORD_TIMESTAMP)
}

func main() {
	showOpcodes()
}
